### ISSUE TITLE
Feature request: option to add link to the tool

### ISSUE THREAD

**Issue by def-gthill** [Neonnaut/Neonnaut.github.io#1]
I've started using this tool to create glosses on my website, and I'm impressed with what I've seen so far. I want to acknowledge your contribution, so I've included a link to the page below the gloss:
![Gloss My Gloss](https://user-images.githubusercontent.com/5505409/123555083-bdf8a580-d740-11eb-9ecf-c7720732cca7.png)
Could there be an option to have the tool generate something like this, so I don't have to copy it for each gloss?

**Comment by Neonnaut** [comment]
I've added it, tell me if that's what you had in mind. And thank you for the kind words.

**Comment by def-gthill** [comment]
Cool, that was the idea. Can the line have its own class too so I can target it with CSS (e.g. making it smaller so it's less obtrusive)?

**Comment by Neonnaut** [comment]
Done it, the class is called 'gmg-ack'.

**Comment by def-gthill** [comment]
Amazing, thanks!
